shutdown_timeout: 5s

grpc:
  host: 0.0.0.0
  port: 50051

logger:
  level: info

service:
  accuracy: 10

  min_interval: 1
  max_interval: 300

  min_period: 1
  max_period: 300

  disabled_providers:
    #- loadavg
    #- cpuload
