// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v4.25.2
// source: stats/v1/stats_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetSupportedStatsRequest запрос на получение поддерживаемых провайдеров статистики.
type GetSupportedStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSupportedStatsRequest) Reset() {
	*x = GetSupportedStatsRequest{}
	mi := &file_stats_v1_stats_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupportedStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupportedStatsRequest) ProtoMessage() {}

func (x *GetSupportedStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupportedStatsRequest.ProtoReflect.Descriptor instead.
func (*GetSupportedStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_service_proto_rawDescGZIP(), []int{0}
}

// GetSupportedStatsResponse ответ с данными о поддерживаемых провайдерах статистики.
type GetSupportedStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Provider информация о провайдере статистики.
	Provider *Provider `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
}

func (x *GetSupportedStatsResponse) Reset() {
	*x = GetSupportedStatsResponse{}
	mi := &file_stats_v1_stats_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupportedStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupportedStatsResponse) ProtoMessage() {}

func (x *GetSupportedStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupportedStatsResponse.ProtoReflect.Descriptor instead.
func (*GetSupportedStatsResponse) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetSupportedStatsResponse) GetProvider() *Provider {
	if x != nil {
		return x.Provider
	}
	return nil
}

// GetStatsRequest запрос на получение статистики за период period каждые interval секунд.
type GetStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Interval интервал получения статистики.
	Interval int64 `protobuf:"varint,1,opt,name=interval,proto3" json:"interval,omitempty"`
	// Period период, за который будет выдаваться статистика.
	Period int64 `protobuf:"varint,2,opt,name=period,proto3" json:"period,omitempty"`
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_stats_v1_stats_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatsRequest) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *GetStatsRequest) GetPeriod() int64 {
	if x != nil {
		return x.Period
	}
	return 0
}

// GetStatsResponse ответ с данными статистики или возникшей ошибкой.
type GetStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Body данные или ошибка.
	//
	// Types that are assignable to Body:
	//
	//	*GetStatsResponse_Record
	//	*GetStatsResponse_Error
	Body isGetStatsResponse_Body `protobuf_oneof:"body"`
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_stats_v1_stats_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stats_v1_stats_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_stats_v1_stats_service_proto_rawDescGZIP(), []int{3}
}

func (m *GetStatsResponse) GetBody() isGetStatsResponse_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *GetStatsResponse) GetRecord() *Record {
	if x, ok := x.GetBody().(*GetStatsResponse_Record); ok {
		return x.Record
	}
	return nil
}

func (x *GetStatsResponse) GetError() string {
	if x, ok := x.GetBody().(*GetStatsResponse_Error); ok {
		return x.Error
	}
	return ""
}

type isGetStatsResponse_Body interface {
	isGetStatsResponse_Body()
}

type GetStatsResponse_Record struct {
	// Record данные статистики.
	Record *Record `protobuf:"bytes,1,opt,name=record,proto3,oneof"`
}

type GetStatsResponse_Error struct {
	// Error возникшая ошибка (наприме, ошибка валидации запроса).
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetStatsResponse_Record) isGetStatsResponse_Body() {}

func (*GetStatsResponse_Error) isGetStatsResponse_Body() {}

var File_stats_v1_stats_service_proto protoreflect.FileDescriptor

var file_stats_v1_stats_service_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x14, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1a,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4b, 0x0a, 0x19, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x61, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x52, 0x08, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0x45, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x22, 0x5e,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x16,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x32, 0xb1,
	0x01, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x5c, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x12, 0x22, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x70, 0x70, 0x6f, 0x72, 0x74, 0x65, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a,
	0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x19, 0x2e, 0x73, 0x74, 0x61, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x30, 0x01, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x69, 0x6d, 0x61, 0x2d, 0x73, 0x74, 0x75, 0x64, 0x79, 0x2f, 0x6d, 0x6f, 0x6e, 0x6d,
	0x6f, 0x6e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x74, 0x61, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_stats_v1_stats_service_proto_rawDescOnce sync.Once
	file_stats_v1_stats_service_proto_rawDescData = file_stats_v1_stats_service_proto_rawDesc
)

func file_stats_v1_stats_service_proto_rawDescGZIP() []byte {
	file_stats_v1_stats_service_proto_rawDescOnce.Do(func() {
		file_stats_v1_stats_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_stats_v1_stats_service_proto_rawDescData)
	})
	return file_stats_v1_stats_service_proto_rawDescData
}

var file_stats_v1_stats_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_stats_v1_stats_service_proto_goTypes = []any{
	(*GetSupportedStatsRequest)(nil),  // 0: stats.v1.GetSupportedStatsRequest
	(*GetSupportedStatsResponse)(nil), // 1: stats.v1.GetSupportedStatsResponse
	(*GetStatsRequest)(nil),           // 2: stats.v1.GetStatsRequest
	(*GetStatsResponse)(nil),          // 3: stats.v1.GetStatsResponse
	(*Provider)(nil),                  // 4: stats.v1.Provider
	(*Record)(nil),                    // 5: stats.v1.Record
}
var file_stats_v1_stats_service_proto_depIdxs = []int32{
	4, // 0: stats.v1.GetSupportedStatsResponse.provider:type_name -> stats.v1.Provider
	5, // 1: stats.v1.GetStatsResponse.record:type_name -> stats.v1.Record
	0, // 2: stats.v1.StatsService.GetSupportedStats:input_type -> stats.v1.GetSupportedStatsRequest
	2, // 3: stats.v1.StatsService.GetStats:input_type -> stats.v1.GetStatsRequest
	1, // 4: stats.v1.StatsService.GetSupportedStats:output_type -> stats.v1.GetSupportedStatsResponse
	3, // 5: stats.v1.StatsService.GetStats:output_type -> stats.v1.GetStatsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stats_v1_stats_service_proto_init() }
func file_stats_v1_stats_service_proto_init() {
	if File_stats_v1_stats_service_proto != nil {
		return
	}
	file_stats_v1_stats_proto_init()
	file_stats_v1_stats_service_proto_msgTypes[3].OneofWrappers = []any{
		(*GetStatsResponse_Record)(nil),
		(*GetStatsResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stats_v1_stats_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stats_v1_stats_service_proto_goTypes,
		DependencyIndexes: file_stats_v1_stats_service_proto_depIdxs,
		MessageInfos:      file_stats_v1_stats_service_proto_msgTypes,
	}.Build()
	File_stats_v1_stats_service_proto = out.File
	file_stats_v1_stats_service_proto_rawDesc = nil
	file_stats_v1_stats_service_proto_goTypes = nil
	file_stats_v1_stats_service_proto_depIdxs = nil
}
